### ISSUE TITLE
Type issue in oneOf schemas

### ISSUE THREAD

**Issue by sceccotti89** [ThomasAribart/json-schema-to-ts#116]
In a oneOf schema, the most nested property is not properly typed by TS.

Example:

```js
const catSchema = {
  type: 'object',
  properties: {
    cat_property: {
      type: 'object',
      oneOf: [
        {
          properties: {
            name: { type: 'string' },
          },
          required: ['name'],
        },
        {
          properties: {
            color: { type: 'string', enum: ['black', 'brown', 'white'] },
          },
        },
      ],
    },
  },
} as const;

type Cat = FromSchema<typeof catSchema>;
const cat: Cat = { cat_property: { name: 'My name' } };
cat.cat_property.name; // This is considered unknown instead of string.
```

If I hover over the **Cat** type, everything looks fine:

```js
type Cat = {
    [x: string]: unknown;
    cat_property: {
        [x: string]: unknown;
        name: string;
    } | {
        [x: string]: unknown;
        color?: "black" | "brown" | "white" | undefined;
    };
}
```

But when I try to access the name attribute, TS says it's **unknown**.

Is it a bug of the library or it's due to Typescript?

**Comment by giraffesyo** [comment]
Looks like you need to set `additionalProperties: false,`, along with the `oneOf`.

**Comment by sceccotti89** [comment]
@giraffesyo 

Thanks for the response but it's still not working.
This is the updated schema:

```js
const catSchema = {
  type: 'object',
  additionalProperties: false,
  oneOf: [
    {
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
      },
      required: ['name'],
    },
    {
      additionalProperties: false,
      properties: {
        color: { type: 'string', enum: ['black', 'brown', 'white'] },
      },
    },
  ],
}
```

I tried all the possible combinations but non of them worked.
Were you able to test it yourself and make it works?

I forgot to share details about my environment.
I'm using Typescript v4.9.5 and node v16.17.1

**Comment by ThomasAribart** [comment]
Hi @sceccotti89 !

I think it was a bug that appeared in v2.5.5. Can you try again with v2.7.2 ? It seems like it's fixed

**Comment by ThomasAribart** [comment]
Hi @sceccotti89 !

Several elements here:
- The second schema you provided will not really work as the `additionalProperties` at the root level will apply to an "invisible" `properties: {}` keyword, and thus deny `name` and `color`property. The only possibility is to follow the second children but with `color?: undefined`. You probably want to remove it.
- In the first schema, the problem you encounter is due to Typescript. Technically, the `cat_property` is a union of two cases, A (`name`) or B (`color`). In your context, event if your `cat` const has a name property, it is typed as `Cat` and TS will not take it for granted. Thus, when you try to access the `name` property, TS still considers that it can be `string` in case A or `unknown` in case B. `string` extends `unknown` so `unknown` wins.

You can try to not assign the `Cat` type to your `cat` const but simply make sure it satisfies it:
```typescript
const cat = { cat_property: { name: 'My name' } } satisfies Cat
```
