### ISSUE TITLE
Possible regression in 2.9.0

### ISSUE THREAD

**Issue by mhio** [ThomasAribart/json-schema-to-ts#144]
When using json-schema-to-ts via [@fastify/fastify-type-provider-json-schema-to-ts](https://github.com/fastify/fastify-type-provider-json-schema-to-ts) the 2.9.0 release is producing issues converting schemas to types. 

I only raise this issue here as 2.9.0 doesn't appear to be a feature release, just a change in the release process, so I thought a change in behaviour would be of interest here. 

https://github.com/fastify/fastify-type-provider-json-schema-to-ts/issues/49

Similar to #132 but I couldn't reproduce the issue in fastify-type-provider-json-schema-to-ts depending on 2.8.0, 2.8.1 or 2.8.2 so appears on the surface to be something different.

**Comment by aardvarkk** [comment]
I'm seeing the same issue as Fastify around "Type instatiation is excessively deep and possibly infinite". Reverting to v2.8 fixes the issue.

**Comment by ThomasAribart** [comment]
Thanks for the heads up! Very weird indeed as there has been no change in the source code between 2.8.2 and 2.9, only CI/CD stuff. Will be looking at that tomorrow!

**Comment by tizmagik** [comment]
I was getting this same error and I had to downgrade to exactly 2.8.0 for it to work. TypeScript v5.0.4

**Comment by Physicliar** [comment]
I am using serverless framework aws-serverless-typescript template and getting the same error event 2.8.0 or 2.9.0 or even 2.7.0. 

TypeScript v5.0.4

**Comment by ThomasAribart** [comment]
@Physicliar It was fixed in 2.8.2 I think

**Comment by ThomasAribart** [comment]
Just looked at it, the builds of [2.8.2](https://www.npmjs.com/package/json-schema-to-ts/v/2.8.2?activeTab=code) and [2.9.0](https://www.npmjs.com/package/json-schema-to-ts/v/2.9.0?activeTab=code) are exactly the same, except that in 2.8.2, all types are declared and not in not in 2.9.0.

<img width="979" alt="yo ts — castore (Workspace) 2023-05-27 11-29-43" src="https://github.com/ThomasAribart/json-schema-to-ts/assets/38014240/38f1038e-1bca-4ec0-856f-1bc71923b5ed">

I'm not sure why exactly, but it's probably what caused the regression (it's the only diff I see anyway). It seems it came from [using the v4.9.5](https://github.com/ThomasAribart/json-schema-to-ts/pull/141/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R41) of TS to build the types instead of the `^4.5.5`. Will try to fix that ASAP.

**Comment by ThomasAribart** [comment]
@mhio @aardvarkk @tizmagik @Physicliar Can you try with 2.9.1 ? The `declare` are now back so the code should be exactly the same as 2.8.2.

Strangely, it also solved a deno build issue (here 2.9.0 vs 2.9.1):

<img width="1053" alt="v2 9 0 🌈 · ThomasAribart:json-schema-to-ts@e211f20 2023-05-27 12-01-14" src="https://github.com/ThomasAribart/json-schema-to-ts/assets/38014240/c82fa452-04e8-4bab-ad4b-d939acc59393">

<img width="726" alt="v2 9 1 🌈 · ThomasAribart:json-schema-to-ts@01f639b 2023-05-27 12-00-23" src="https://github.com/ThomasAribart/json-schema-to-ts/assets/38014240/feac383a-36cf-41c8-bb1d-5483fa4748ae">

**Comment by aardvarkk** [comment]
@ThomasAribart I can confirm that upgrading from 2.9.0 to 2.9.1 fixes the "Type instantiation is excessively deep and possibly infinite" issue for me.

**Comment by ThomasAribart** [comment]
Great 👍 Closing this issue then!

**Comment by mhio** [comment]
Thanks Thomas!
