### ISSUE TITLE
Default attribute should make the property required

### ISSUE THREAD

**Issue by sceccotti89** [ThomasAribart/json-schema-to-ts#153]
Currently a schema like this:

```js
{
  type: "object",
  properties: {
    value: { type: "number", default: 5 },
  },
}
```

results in this type:

```js
{
  [x: string]: unknown;
  value?: number | undefined;
}
```

I believe that a property with a defined default value should be treated as not optional, resulting in a type like the following:

```js
{
  [x: string]: unknown;
  value: number;
}
```

What do you think?

**Comment by ThomasAribart** [comment]
Hmm I think it really depends on the context. Consider those two cases:

- I handle validated value => `value` should be required
- I input raw value (not validated) to a form or HTTP endpoint => `value` should be optional

So I think it should be configured through an option: `FromSchema<mySchema, { someOption: boolean }>` 

The question now is what is default behavior of `FromSchema` ? I feel like it's more frequent to use `FromSchema` for validated values rather than inputs, so the option should be `{ keepDefaultedValuesOptional: true }` ? That's a breaking change but a rather small one so I would be OK with implementing it.

WDYT ?

**Comment by sceccotti89** [comment]
I think it totally make sense.
I tried to do it myself but this thing it's still a bit magic to me. It would be great you can take care of that 🙏

**Comment by iamarthurk** [comment]
Much needed a feature guys, let me know if it is on the roadmap or whether you are open to pull requests.

**Comment by ThomasAribart** [comment]
Feature is now available in the v3: https://github.com/ThomasAribart/json-schema-to-ts/issues/153 🙌

Wasn't so long to implement, sorry for the delay !

**Comment by davidmurdoch** [comment]
> I feel like it's more frequent to use FromSchema for validated values rather than inputs

Interesting take. I think the use case of pre/post validation would be 50/50. The interface/function doing the validation of the raw data would need `default`-less types.

In my specific case I don't need to validate the data _with_ defaults applied, since I'm calling into another API that will apply necessary defaults for me.

Of course this change doesn't really causes any issues, since the `keepDefaultedPropertiesOptional` option was also added, I just wanted to offer additional perspective on how this (awesome!) library is being used out in the wild. 🚀
