### ISSUE TITLE
Schema Schema

### ISSUE THREAD

**Issue by jonathan-meyer** [ThomasAribart/json-schema-to-ts#6]
Is there a Schema for the Schema?

```
const fooSchema : JsonSchema = {
  type: "object",
  properties: {
    bar: { type: "number" },
    type: { enum: ["one", "two", "tree"] },
  },
  required: ["bar", "type"],
} as const;
```

**Comment by ThomasAribart** [comment]
Hi @jonathan-meyer,

Hi Jonathan,

It seems like https://www.npmjs.com/package/@types/json-schema would do the trick.

However, it will not work with json-schema-to-ts, as `FromSchema` needs the hard type of the schema to do the parsing. Here, `type` should be typed as the `"object"` string and not a general string or a union of string containing `"object"`, which would be the case if you assign `JsonSchema` to `fooSchema.`

It would be neat to check if the generic type given to `FromSchema` extends the `JsonSchema` type given by definitely typed, which would both:
- Trigger an error if the schema is not correct
- Leave the hard type parsable

I'll try to implement that, good suggestion 👍

**Comment by ThomasAribart** [comment]
Hi @jonathan-meyer,

Since v1.4.0, `FromSchema` now checks that your schema extends DefinitelyTyped's definitions before parsing it 🎉 Thus, giving you a clear error on what's wrong.

<img width="440" alt="yo ts — safetracker 2020-11-28 20-00-27" src="https://user-images.githubusercontent.com/38014240/100524151-13260600-31b6-11eb-9dac-dc0c1fbbfa99.png">

You won't have all the benefits that you would gain from assigning DefinitelyTyped's definitions to your schema (autocomplete, highlighted invalid keyword...), but as I mentioned, they are not implementable anyway. What you can still do though, is to assign DefinitelyTyped's definitions to your schema first, then when you're finished writing it, unassign them and use `as const` and `FromSchema`.
